encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - CNAME

#Ensure capatibility with Github Pages
safe: true

collections:
  - links

#Misc Settings
google_analytics_id: UA-484023-10

description: "Film Production based in Brisbane, Australia."
keywords: "film, movies, video, editing, producing"
author: "David Peterson"

groups:
  - film
  - about
