encoding: UTF-8
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - CNAME

#Ensure capatibility with Github Pages
safe: true

collections:
  - alone_faqs
  - links
  - escape_credits
  - escape_faqs
  - spacex_faqs

#Misc Settings
google_analytics_id: UA-484023-10

description: "Screenwriting, editing, and producing, based in Brisbane, Australia."
keywords: "film, movies, video, editing, writing, screenwriting, producing"
author: "David Peterson"

groups:
  - film
  - about
